<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'Entity\\Cliente' . "\0" . 'apelido', '' . "\0" . 'Entity\\Cliente' . "\0" . 'cpf', '' . "\0" . 'Entity\\Cliente' . "\0" . 'sexo', '' . "\0" . 'Entity\\Cliente' . "\0" . 'nascimento', '' . "\0" . 'Entity\\Cliente' . "\0" . 'telefone_contato', '' . "\0" . 'Entity\\Cliente' . "\0" . 'telefone_celular', '' . "\0" . 'Entity\\Cliente' . "\0" . 'foto', '' . "\0" . 'Entity\\Cliente' . "\0" . 'data_cadastro', '' . "\0" . 'Entity\\Cliente' . "\0" . 'observacao', '' . "\0" . 'Entity\\Cliente' . "\0" . 'endereco'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'Entity\\Cliente' . "\0" . 'nome', '' . "\0" . 'Entity\\Cliente' . "\0" . 'email', '' . "\0" . 'Entity\\Cliente' . "\0" . 'apelido', '' . "\0" . 'Entity\\Cliente' . "\0" . 'cpf', '' . "\0" . 'Entity\\Cliente' . "\0" . 'sexo', '' . "\0" . 'Entity\\Cliente' . "\0" . 'nascimento', '' . "\0" . 'Entity\\Cliente' . "\0" . 'telefone_contato', '' . "\0" . 'Entity\\Cliente' . "\0" . 'telefone_celular', '' . "\0" . 'Entity\\Cliente' . "\0" . 'foto', '' . "\0" . 'Entity\\Cliente' . "\0" . 'data_cadastro', '' . "\0" . 'Entity\\Cliente' . "\0" . 'observacao', '' . "\0" . 'Entity\\Cliente' . "\0" . 'endereco'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getApelido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApelido', []);

        return parent::getApelido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApelido($apelido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApelido', [$apelido]);

        return parent::setApelido($apelido);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNascimento', []);

        return parent::getNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNascimento($nascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNascimento', [$nascimento]);

        return parent::setNascimento($nascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneContato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneContato', []);

        return parent::getTelefoneContato();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneContato($telefone_contato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneContato', [$telefone_contato]);

        return parent::setTelefoneContato($telefone_contato);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefoneCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefoneCelular', []);

        return parent::getTelefoneCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefoneCelular($telefone_celular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefoneCelular', [$telefone_celular]);

        return parent::setTelefoneCelular($telefone_celular);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', []);

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', []);

        return parent::setDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', []);

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', []);

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', [$observacao]);

        return parent::setObservacao($observacao);
    }

}
