<?php $this->plugin('basePath')->setBasePath($this->basePath() . '/public'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        Essentia Pharma - Meus Clientes
    </title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="<?= $this->basePath('js/plugins/nucleo/css/nucleo.css'); ?>" rel="stylesheet"/>
    <link href="<?= $this->basePath('js/plugins/@fortawesome/fontawesome-free/css/all.min.css'); ?>" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="<?= $this->basePath('css/style.min.css?v=1.1.0'); ?>" rel="stylesheet"/>
    <link href="<?= $this->basePath('css/jquery.dataTables.min.css'); ?>" rel="stylesheet"/>
    <!--   Core   -->
    <script src="<?= $this->basePath('js/plugins/jquery/dist/jquery.min.js'); ?>"></script>
    <!--   DataTable JS   -->
    <script src="<?= $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>
    <!-- Maskmoney -->
    <script src="<?= $this->basePath('js/jquery.mask.min.js'); ?>"></script>
    <script src="<?= $this->basePath('js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js'); ?>"></script>
    <!--   Optional JS   -->
    <script src="<?= $this->basePath('js/plugins/chart.js/dist/Chart.min.js'); ?>"></script>
    <script src="<?= $this->basePath('js/plugins/chart.js/dist/Chart.extension.js'); ?>"></script>
    <!--   Argon JS   -->
    <script src="<?= $this->basePath('js/argon-dashboard.js'); ?>"></script>
</head>

<body class="">

<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
                aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0 collapse-brand" href="">
            <strong style="color: #5e72e4">Essentia Pharma</strong>
        </a>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="">
                            <strong>Essentia Pharma</strong>
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                                data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                                aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item  class=active">
                    <a class="nav-link" href="<?= $this->url('Inicial'); ?>"> <i
                                class="ni ni-tv-2 text-primary"></i> Inicial </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link " href="<?= $this->url('ClienteLista'); ?>">
                        <i class="fa fa-user text-red"></i> Clientes
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="main-content">
    <!-- Navbar -->

    <!-- End Navbar -->
    <!-- Header -->
    <?= $this->content ?>
    <p></p>
</div>
<script>
    $(document).ready(function () {
        $('.dataTable').DataTable();
    });
</script>
</body>
</html>