<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="<?= $this->url('ClienteLista') ?>">Clientes </a>
    </div>
</nav>
<div class="header bg-gradient-primary pb-5 pt-6 pt-md-0">
</div>
<div class="main-content">
    <div class="container-fluid">
        <div class="">
            <div class="row mt-5">
                <div class="col-xl-12 mb-5 mb-xl-0">

                    <?php if ($this->msgs): ?>
                        <div class="alert alert-success" role="alert">
                            <strong>Sucesso!</strong> <?= $this->msgs; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->msge): ?>
                        <div class="alert alert-danger" role="alert">
                            <strong>Erro!</strong> <?= $this->msge; ?>
                        </div>
                    <?php endif; ?>

                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col col-md-12">
                                    <h3 class="mb-0"><span class="fa fa-box"></span> Cadastro de Clientes</h3>
                                </div>
                            </div>
                            <form action="" method="post" enctype="multipart/form-data">
                                <div class="row">
                                    <p></p>
                                    <div class="col col-md-12">
                                        </br>
                                        <nav>
                                            <div class="nav-wrapper">
                                                <ul class="nav nav-pills nav-fill flex-column flex-md-row"
                                                    id="tabs-icons-text" role="tablist">
                                                    <li class="nav-item">
                                                        <a class="nav-link mb-sm-3 mb-md-0 active"
                                                           id="tabs-icons-text-1-tab" data-toggle="tab"
                                                           href="#tabs-icons-text-1" role="tab"
                                                           aria-controls="tabs-icons-text-1" aria-selected="true"><i
                                                                    class="ni ni-diamond mr-2"></i>Dados</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link disabled bg-default mb-sm-3 mb-md-0" id="tabs-icons-text-2-tab"
                                                           data-toggle="tab" href="#tabs-icons-text-2" role="tab"
                                                           aria-controls="tabs-icons-text-2" aria-selected="false" title="O endereço será habilitado após o cadastro do cliente"><i
                                                                    class="fa fa-address-book mr-2"></i>Endereços</a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="card shadow">
                                                <div class="card-body">
                                                    <div class="tab-content" id="myTabContent">
                                                        <div class="tab-pane fade show active" id="tabs-icons-text-1"
                                                             role="tabpanel" aria-labelledby="tabs-icons-text-1-tab">
                                                            <div class="row">
                                                                <div class="col col-md-6">
                                                                    <div class="p-2">
                                                                        Nome Completo <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <input required maxlength="100" type="text"
                                                                                   class="form-control"
                                                                                   id="nome" name="nome"
                                                                                   placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Apelido
                                                                        <div class="form-group">
                                                                            <input maxlength="30" type="text"
                                                                                   class="form-control"
                                                                                   id="apelido" name="apelido"
                                                                                   placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Sexo <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <select name="sexo" id="sexo"
                                                                                    class="form-control" required>
                                                                                <option value="M">Masculino</option>
                                                                                <option value="F">Feminino</option>
                                                                            </select>
                                                                        </div>
                                                                        Telefone Celular <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <input required maxlength="14" type="text"
                                                                                   class="form-control celular"
                                                                                   id="telefone_celular"
                                                                                   name="telefone_celular"
                                                                                   placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Observações
                                                                        <div class="form-group">
                                                <textarea name="observacao" id="observacao" class="form-control"
                                                          rows="3"
                                                          placeholder="Observações do cliente"></textarea>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col col-md-6">
                                                                    <div class="p-2">
                                                                        E-mail <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <input required maxlength="100" type="email" class="form-control"
                                                                                   id="email" name="email" placeholder="Nome do Cliente">
                                                                        </div>
                                                                        CPF <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <input required maxlength="11" type="number" class="form-control cpf"
                                                                                   id="cpf" name="cpf" placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Data de Nascimento <span class="text-red">*</span>
                                                                        <div class="form-group">
                                                                            <input required maxlength="10" type="text" class="form-control data"
                                                                                   id="nascimento" name="nascimento" placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Telefone Fixo
                                                                        <div class="form-group">
                                                                            <input maxlength="13" type="text" class="form-control fixo"
                                                                                   id="telefone_contato" name="telefone_contato"
                                                                                   placeholder="Nome do Cliente">
                                                                        </div>
                                                                        Foto
                                                                        <div class="form-group">
                                                                            <input type="file" name="foto" id="foto" class="form-control">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="tab-pane fade" id="tabs-icons-text-2"
                                                             role="tabpanel" aria-labelledby="tabs-icons-text-2-tab">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                    </div>
                                    <div class="col col-md-12">
                                        </br>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success"><span
                                                        class="fa fa-plus"></span> Cadastrar Cliente
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('.celular').mask('(99)99999-9999');
        $('.fixo').mask('(99)9999-9999');
        $('.data').mask('99/99/9999');
        $('.cpf').mask('99999999999');
    });
</script>