<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
        <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="/">Inicial</a>
    </div>
</nav>
<div class="header bg-gradient-primary pb-8 pt-3 pt-md-6">
    <div class="container-fluid">

    </div>
</div>
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col-xl-12 col-md-12">
            <div class="card shadow">
                <div class="card-header bg-transparent">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="text-uppercase text-muted ls-1 mb-1">Clientes</h6>
                            <h2 class="mb-0">Gráfico cadastro de Clientes </h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <!-- Chart -->
                    <div class="chart">
                        <canvas id="chart-orders" class="chart-canvas"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>